// check_error 6:17 "accessing array out-of-bounds with index 5, array size is 5"
extern func foo() -> int[5]&;

func main() {
    const p = foo();
    const e = p[5];
}
