// check_error 5:7 "invalid argument name 'foo' for parameter 'a'"

func f(int a) { }
func main() {
    f(foo = 0);
}
