// check_error 4:9 "256 is out of range for type 'uint8'"
func foo(a: uint8) { }
func main() {
    foo(256);
}
