// check_error 4:12 "no matching function for call to 'f'"
func f(foo: int a, bar: bool b) -> int { return a; }
func main() -> int {
    return f(foo: 5, qux: false);
}
