// check_error 3:23 "no matching function for call to 'foo'"
func fooz() -> int { return 42; }
func main() { var i = foo(); }
