// compile_and_run_and_check_exit_status 42
func _foo() -> int { return 42; }
func main() -> int { return _foo(); }
